### ISSUE TITLE
Problem getting tinder access token

### ISSUE THREAD

**Issue by mrandrewandrade** [zachlatta/pyre#2]
When I follow the link, I get the following:

Success 
SECURITY WARNING: Please treat the URL above as you would your password and do not share it with anyone. See the Facebook Help Center for more information.\

Where is the access token located?

**Comment by ayancey** [comment]
This is a safety feature that prevents people from unsuspectingly giving their access token to malicious websites or apps. You need to quickly copy the location bar (URL) before the warning pops up.
The URL will look something like: https://www.facebook.com/connect/login_success.html#access_token=blahblahblahblahblahblah&expires_in=3614 where **blahblahblahblahblahblah** is your token.

**Comment by mrandrewandrade** [comment]
I found an easier solution.  Can I edit the .md fine and send a pull request?

**Comment by zachlatta** [comment]
Please!
